// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9KMqQ74xL0aF35RvJDS-zK55zFZH1PGw',
    appId: '1:1088424424163:web:b372a3b488b8c9ecfe4bd6',
    messagingSenderId: '1088424424163',
    projectId: 'sprint2-85511',
    authDomain: 'sprint2-85511.firebaseapp.com',
    storageBucket: 'sprint2-85511.firebasestorage.app',
    measurementId: 'G-1JKJ9JT9E8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOyktdFAKTejNclTEGMBaB7iWusf7oDrg',
    appId: '1:1088424424163:android:83f7ebbff1c9c2f1fe4bd6',
    messagingSenderId: '1088424424163',
    projectId: 'sprint2-85511',
    storageBucket: 'sprint2-85511.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPVCqjrsuCcxs_qCL5-9ZF3qq0DlwiFBA',
    appId: '1:1088424424163:ios:c1f568bc526debd7fe4bd6',
    messagingSenderId: '1088424424163',
    projectId: 'sprint2-85511',
    storageBucket: 'sprint2-85511.firebasestorage.app',
    iosBundleId: 'com.example.sprint2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPVCqjrsuCcxs_qCL5-9ZF3qq0DlwiFBA',
    appId: '1:1088424424163:ios:c1f568bc526debd7fe4bd6',
    messagingSenderId: '1088424424163',
    projectId: 'sprint2-85511',
    storageBucket: 'sprint2-85511.firebasestorage.app',
    iosBundleId: 'com.example.sprint2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9KMqQ74xL0aF35RvJDS-zK55zFZH1PGw',
    appId: '1:1088424424163:web:185f18f93809e01efe4bd6',
    messagingSenderId: '1088424424163',
    projectId: 'sprint2-85511',
    authDomain: 'sprint2-85511.firebaseapp.com',
    storageBucket: 'sprint2-85511.firebasestorage.app',
    measurementId: 'G-FCV51ZF1N1',
  );
}
